---

- name: removing the files and folder
  hosts: all
  become: true
  tasks:
          - name: remove the files

            
            command: rm -rf *
            args:
                    chdir: /home/ec2-user/pemkeys


          - name: remove folder
            command: rm -rf pemkeys


