---

- name: run play2
  hosts: targethost
  become: yes
  tasks:
          - name: Install pip
            yum:
                    name: python3-pip
                    state: present

 
                     
          - name: Pull an image
            docker_image:
                    name: ubuntu

